### ISSUE TITLE
dw_client segfault

### ISSUE THREAD

**Issue by tomcucinotta** [tomcucinotta/distwalk#51]
```
./dw_node &
./dw_client --num-threads=50
[...]
t: 1072 us, elapsed: 205068 us, req_id: 0, thr_id: 14, sess_id: 0
RECV Unexpected error: Socket operation on non-socket
RECV Unexpected error: Socket operation on non-socket
Segmentation fault (core dumped)
```

**Comment by deRemo** [comment]
We introduced too much statically allocated memory. Currently (commit bed248f) I'm at 2GB of bss memory for dw_client's binary file on my laptop:

```
remo@x1:~/Repositories/distwalk/src$ size dw_client
   text	   data	        bss	               dec	                 hex	filename
  45321	   3248	2056724688	2056773257	7a97de89	dw_client
```

**Comment by deRemo** [comment]
Fixed here 64fee52968430b74314ec2741882e755c0ff72b7

**Comment by tomcucinotta** [comment]
the crash is still there, just reproduced on commit 885ca987, same simple recipe as above.

**Comment by tomcucinotta** [comment]
Fixed with commit 9fd8bf5, closing.
